name: cd

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Deployment target'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
  workflow_call:
    inputs:
      environment_name:
        required: true
        default: 'dev'
        type: string
  push:
    branches:
      - feature/**

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './app/func'
  PYTHON_VERSION: '3.11'
  ARTIFACT_NAME: 'func'
  DOWNLOAD_ARTIFACT_DIRPATH: 'artf'

jobs:
  upload-artifact:
    runs-on: ubuntu-22.04
    environment: §{{ inputs.environment_name == && dev || inputs.environment_name }}
    defaults:
      run:
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    steps:
    - name: Checkout GitHub Action. ${{ inputs.environment_name == '' && 'dev' || inputs.environment_name }} environment.
      uses: actions/checkout@v4
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    # Dependencies are installed in the .python_packages directory（これがないとAzure Functionsの関数が表示されない
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
    - name: Display structure
      shell: bash
      run: ls -R
    - name: Upload artifact for deployment jobs
      uses : actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name == '' && env.ARTIFACT_NAME || inputs.artifact_name }}
        path: |
          ./app/func
          !.gitignore
        include-hidden-files: true # 隠しファイル追加オプション

  # deploy application
  # https://docs.github.com/ja/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
  deploy:
    needs: upload-artifact
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment_name == '' && 'dev' || inputs.environment_name }}
    steps:
      - name: Download artifact for deployment jobs. ${{ inputs.environment_name == '' && 'dev' || inputs.environment_name }} environment. artifact name is ${{ inputs.artifact_name == '' && env.ARTIFACT_NAME || inputs.artifact_name }}.
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact_name == '' && env.ARTIFACT_NAME || inputs.artifact_name }}
          path: ${{ env.DOWNLOAD_ARTIFACT_DIRPATH }}
      - name: Display structure
        shell: bash
        run: ls -R
      - name: Run Azure Functions Action. ${{ inputs.environment_name == '' && 'dev' || inputs.environment_name }} environment. function name is ${{ vars.AZURE_FUNCTIONAPP_NAME }}
        uses: Azure/functions-action@v1.5.2
        id: deploy-to-function
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.DOWNLOAD_ARTIFACT_DIRPATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          sku: flexconsumption
          remote-build: false

#
# name: deploy function App

# on:
#   workflow_call:
#     inputs:
#       artifact_name:
#         required: true
#         type: string
 

# env:
#   AZURE_FUNCTIONAPP_NAME: 'func-dev-pj'   # set this to your function app name on Azure
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
#   PYTHON_VERSION: '3.11'

# jobs:
#   deploy:
#     runs-on: ubuntu-22.04
#     environment: dev
#     steps:
#       - name: Display structure
#         shell: bash
#         run: ls -R

#       - uses: actions/download-artifact@v4
#         with:
#           name: ${{ inputs.artifact_name }}
#           path: artifact
      
#       - name: Display structure of downloaded files
#         shell: bash
#         run: ls -R
        
#       # - name: Unzip artifact for deployment
#       #   run: unzip ./artifact/release.zip
      
#       - name: 'Run Azure Functions Action'
#         uses: Azure/functions-action@v1
#         id: deploy-to-function
#         with:
#           app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#           package: ./artifact/release.zip
#           publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
#           scm-do-build-during-deployment: true
#           enable-oryx-build: true
