name: Deploy Python project to Azure Function App

on:
  workflow_call:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_NAME: 'func-dev-pj'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './app/func'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
