name: deploy function App

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
 

env:
  AZURE_FUNCTIONAPP_NAME: 'func-dev-pj'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: artifact
      
      - name: Display structure of downloaded files
        shell: bash
        run: ls -R
        
      # - name: Unzip artifact for deployment
      #   run: unzip ./artifact/release.zip
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./artifact/release.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
