name: build function app

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_NAME: 'func-dev-pj'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'app/func'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-application:
    runs-on: ubuntu-22.04
    environment: dev
    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.artifact }}
    defaults:
      run:
        working-directory: ./app/func
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x64'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name : Zip artifact for deployment
      run : zip release.zip ./* -r
      
    - name : Upload artifact for deployment jobs
      uses : actions/upload-artifact@v4.0.0
      with:
        name : python-app
        path : |
          release.zip
          !venv/
    - name : make artifact
      id: artifact-name
      run: |
        echo "artifact=python-app" >> $GITHUB_OUTPUT
# cd workflow
  call-deploy:
    needs: 
      [
        build-application
      ]
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      artifact_name: ${{needs.build-application.outputs.artifact-name}}